name: "Terraform"

on: 
  push:
    branches:
      - master

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
      AWS_ACESS_KEY_ID: ${{ secrets.AWS_ACESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    defaults:
      run:
        working-directory: 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt 
        run: terraform fmt -check 

      - name: Terraform init
        id: init
        run: terraform init 

      - name: Terraform plan
        id: plan 
        run: terraform plan -no-color

      - name: Terraform Apply 
        run: terrafrom apply -auto-approve