name: "Terraform"

on: 
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read      

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4  

      - name: get aws permissions
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          role-to-assume: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/github-infra
          aws-region: eu-west-2  

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"
          terraform_wrapper: false

      - name: Terraform init
        id: init
        run: terraform init 
        working-directory: aws-deploy

      - name: Terraform plan
        id: plan 
        run: terraform plan
        working-directory: aws-deploy
        
      - name: Terraform destroy 
        run: terraform destroy -auto-approve
        working-directory: aws-deploy
    